language: r
cache: packages
sudo: false
r:
  - bioc-release
  - bioc-devel
warnings_are_errors: false
after_success:
  - pwd
  - cd ..
  - git clone --depth=50 --branch=master https://github.com/bcbio/bcbio_rnaseq_output_example.git
  - mkdir template
  - cd template
  - cp ../bcbio_rnaseq_output_example/setup.R .
  - cp ../bcbioRnaseq/inst/rmarkdown/templates/quality_control/skeleton/skeleton.Rmd .
  - Rscript -e 'devtools::install_local("../bcbioRnaseq")'
  - Rscript -e 'rmarkdown::render("skeleton.Rmd")'
  - ls
