language: r
cache: packages
sudo: false
dist: trusty
warnings_are_errors: false
r:
  - bioc-devel
r_github_packages:
  - lpantano/DEGreport
after_success:
  - Rscript -e 'covr::codecov()'
  - pwd
  - cd ..
  - git clone https://github.com/bcbio/bcbio_rnaseq_output_example.git
  - Rscript -e 'devtools::install_local("../bcbioRNASeq")'
  - Rscript -e 'test_that::test_file("test_reports.R")'
  - mv de.html de-${TRAVIS_BRANCH}.html
  - mv qc.html qc-${TRAVIS_BRANCH}.html
  - cp ../bcbioRNASeq.push.sh push.sh
  - chmod +x push.sh
  - ./push.sh
