# Travis-CI configuration for Bioconductor packages
# https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

r:
  - bioc-release
  - bioc-devel

# blocklist
branches:
  except:
  - develop

before_install:
- openssl aes-256-cbc -K $encrypted_edc1907ba0ad_key -iv $encrypted_edc1907ba0ad_iv -in tests/testthat/token.rds.enc -out tests/testthat/token.rds -d

# r_build_args: "--no-build-vignettes"
# r_check_args: "--no-vignettes"

# Set true before submission to Bioconductor
warnings_are_errors: true

# Temporarily enable when caching Bioconductor packages
# script: true

notifications:
  email:
    on_success: change
    on_failure: change

r_packages:
  - covr
  - hexbin
bioc_packages:
  - BiocCheck

after_success:
  - Rscript -e 'covr::codecov()'
  - R CMD BiocCheck .
  - pwd
  - cd ..
  - git clone https://github.com/bcbio/bcbio_rnaseq_output_example.git
  - cd bcbio_rnaseq_output_example
  - Rscript -e 'devtools::install_local("../bcbioRNASeq")'
  - Rscript -e 'testthat::test_file("test_reports.R")'
  - cd report
  - mv de.html de-${TRAVIS_BRANCH}.html
  - mv qc.html qc-${TRAVIS_BRANCH}.html
  - mv fa.html fa-${TRAVIS_BRANCH}.html
  - cd ..
  - cp ../bcbioRNASeq/.push.sh push.sh
  - chmod +x push.sh
  - ./push.sh
