# Travis-CI configuration for Bioconductor packages
# https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

r:
  - bioc-release
  - bioc-devel

# blocklist
branches:
  except:
  - develop

env:
  global:
    - LINTR_COMMENT_BOT=true
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

# r_build_args: "--no-build-vignettes"
# r_check_args: "--no-vignettes"

# Set true before submission to Bioconductor
warnings_are_errors: true

# Temporarily enable when caching Bioconductor packages
# script: true

notifications:
  email:
  recipients:
      - mike@steinbaugh.com
    on_success: change
    on_failure: always

r_packages:
  - covr
  - hexbin
bioc_packages:
  - BiocCheck
r_github_packages:
  - GuangchuangYu/clusterProfiler
  - jimhester/lintr

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - R CMD BiocCheck .
  - pwd
  - cd ..
  - git clone https://github.com/bcbio/bcbio_rnaseq_output_example.git
  - cd bcbio_rnaseq_output_example
  - Rscript -e 'devtools::install_local("../bcbioRNASeq")'
  - Rscript -e 'testthat::test_file("test_reports.R")'
  - cd report
  - mv de.html de-${TRAVIS_BRANCH}.html
  - mv qc.html qc-${TRAVIS_BRANCH}.html
  - mv fa.html fa-${TRAVIS_BRANCH}.html
  - cd ..
  - cp ../bcbioRNASeq/.push.sh push.sh
  - chmod +x push.sh
  - ./push.sh
